apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
  - image: marketsummary
    context: .
deploy:
  helm:
    releases:
      - name: marketsummary
        wait: true
        chartPath: ./charts/marketsummary
        values:
          image: marketsummary
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
          productName: "{{.PRODUCT_NAME}}"
          nodeEnv: "{{.NODE_ENV}}"
          database.hostname: "{{.DB_HOSTNAME}}"
          database.databaseName: "{{.DB_DATABASE_NAME}}"
        setValues:
          hpa.enabled: true
          canary.enabled: true
profiles:
  - name: local
    activation:
      - kubeContext: docker-desktop
    patches:
      - op: add
        path: /deploy/helm/releases/0/setValues/mongodb.enabled
        value: true
      - op: remove
        path: /deploy/helm/releases/0/setValueTemplates/database.hostname
      - op: add
        path: /deploy/helm/releases/0/setValues/database.hostname
        value: marketsummary-mongodb
      - op: remove
        path: /deploy/helm/releases/0/setValueTemplates/database.databaseName
      - op: add
        path: /deploy/helm/releases/0/setValues/database.databaseName
        value: staging
